version: '3'
services:
  marathon:
    build: .
    container_name: marathon
    env_file:
      - .env
    networks:
      - deploy
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
                - TZ=Asia/Seoul

networks:
  deploy:
    external : true
